name: deno run update-indexes.js
on:
  push:
    branches: "main"
    paths:
      - _data/things.csv
      - .github/workflows/deno-run-update-indexes.yml
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  workflow_run:
    workflows: [Add thing]
    types: [completed]
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  update-indexes:
    if: |
      github.event.workflow_run && github.event.workflow_run.conclusion == 'success' || true
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: "20"
      #     cache: npm
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # - run: npm ci
      - run: deno run -A update-indexes.js
      - uses: stefanzweifel/git-auto-commit-action@v5
